"""
Validate bilayer graphene Hofstadter testing code against MATLAB benchmark.

Benchmark: L2_231_sx1_dag1_conj0_psiconj0_newk.mat
  Generated by debugging_fillin_BG.m with:
    order=[2,3,1], sxflag=1, dagger=1, conj_flag=0, psi_conj=0
    ppmax=4, nlayers=2, v0=28.9, v1=21, g1=340, g3=136
    vb = [b1/pp/2; b2/pp]
"""

import sys
import os
import numpy as np
from scipy.io import loadmat

from hofstadter_testing import do_calc_testing

BENCHMARK = (r"C:\Users\phaney\OneDrive - NIST\Documents\MATLAB"
             r"\Duartes_code\Hofstadter_codes"
             r"\L2_231_sx1_dag1_conj0_psiconj0_newk.mat")


def main():
    if not os.path.isfile(BENCHMARK):
        print(f"Benchmark file not found: {BENCHMARK}")
        sys.exit(1)

    mat = loadmat(BENCHMARK, squeeze_me=True)
    qqset_m = np.atleast_1d(mat['qqset'])
    ppset_m = np.atleast_1d(mat['ppset'])
    eesetK_m = mat['eesetK']
    eesetKp_m = mat['eesetKp']

    n_flux = len(qqset_m)
    ppmax = int(ppset_m.max())
    print(f"Benchmark: {n_flux} flux points, ppmax={ppmax}")
    print(f"  ppset = {ppset_m}")
    print(f"  qqset = {qqset_m}")

    order = [2, 3, 1]
    result = do_calc_testing(
        './input_testing_BG.txt', order,
        sxflag=1, dagger=1, conj_flag=0, psi_conj=0,
        ppmax=ppmax, nlayers_arg=2, nworkers_arg=8)

    eesetK_py = result['eesetK']
    eesetKp_py = result['eesetKp']
    ppset_py = result['ppset']
    qqset_py = result['qqset']

    if not np.array_equal(ppset_py, ppset_m):
        print(f"ERROR: ppset mismatch: py={ppset_py} vs mat={ppset_m}")
        sys.exit(1)
    if not np.array_equal(qqset_py, qqset_m):
        print(f"ERROR: qqset mismatch: py={qqset_py} vs mat={qqset_m}")
        sys.exit(1)

    print(f"\n{'qq/pp':>8}  {'dim_K':>8}  {'dim_Kp':>8}  {'maxerr_K':>12}  {'maxerr_Kp':>12}")
    print("-" * 60)

    all_ok = True
    for i in range(n_flux):
        qq, pp = int(qqset_m[i]), int(ppset_m[i])

        eK_m = np.sort(np.atleast_1d(eesetK_m[i]).flatten())
        eK_py = np.sort(eesetK_py[i].flatten())
        eKp_m = np.sort(np.atleast_1d(eesetKp_m[i]).flatten())
        eKp_py = np.sort(eesetKp_py[i].flatten())

        if len(eK_m) != len(eK_py):
            print(f"  {qq}/{pp}: K dim mismatch: py={len(eK_py)} vs mat={len(eK_m)}")
            all_ok = False
            continue
        if len(eKp_m) != len(eKp_py):
            print(f"  {qq}/{pp}: Kp dim mismatch: py={len(eKp_py)} vs mat={len(eKp_m)}")
            all_ok = False
            continue

        err_K = np.max(np.abs(eK_py - eK_m))
        err_Kp = np.max(np.abs(eKp_py - eKp_m))

        status = "OK" if max(err_K, err_Kp) < 1e-6 else "FAIL"
        if status == "FAIL":
            all_ok = False

        print(f"  {qq}/{pp:>2}     {len(eK_m):>8}  {len(eKp_m):>8}  {err_K:>12.3e}  {err_Kp:>12.3e}  {status}")

    print()
    if all_ok:
        print("ALL PASSED")
    else:
        print("SOME FAILURES - see above")
    return 0 if all_ok else 1


if __name__ == '__main__':
    sys.exit(main())
